version: "2.2"
services:
  jobmanager:
    image: flink:latest
    container_name: flink_jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager     

  taskmanager:
    image: flink:latest
    container_name: flink_taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
    

networks:
  default:
    external:
      name: kafka-network
  secondary:
    external:
      name: cassandra-network
